package com.example.assignment_1_calculator;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.TextView;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        // to access activity_main
        setContentView(R.layout.activity_main);
        // R.string.
        //R.java  is an autogenerated file contain all ids.has all res ids which are integer
//        R.id.button_clear -> target clear button
        // findViewById

       Button num_one =  (Button) findViewById(R.id.button_one);
       Button num_two = (Button) findViewById(R.id.button_two);
       Button numThreeButton = (Button) findViewById(R.id.button_three);
       Button numFourButton = (Button) findViewById(R.id.button_four);
       Button numFiveButton = (Button) findViewById(R.id.button_five);
       Button numSixButton = (Button) findViewById(R.id.button_six);
       Button numSevenButton = (Button) findViewById(R.id.button_seven);
       Button numEightButton = (Button) findViewById(R.id.button_eight);
       Button numNineButton = (Button) findViewById(R.id.button_nine);
       Button numZeroButton = (Button) findViewById(R.id.button_zero);

       Button plusButton = (Button) findViewById(R.id.button_plus);
       Button minusButton = (Button) findViewById(R.id.button_minus);
       Button multiplyButton = (Button) findViewById(R.id.button_multiply);
       Button divideButton = (Button) findViewById(R.id.button_divide);

       Button equalToButton = (Button) findViewById(R.id.button_equal);
       Button clearButton = (Button) findViewById(R.id.button_clear);

       TextView resultText = (TextView) findViewById(R.id.result);

//       To set the text there are 2 way first in string resource declare string with name result
//<string name ="result">The result of the operation is</string>
//        resultText.setText(R.string.value);
//        resultText.setText("The sum of two num is ");
        // we can also set color and background value using resources like this



        // add click listener to buttons

        plusButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Log.d("CAL app","add button clicked");

            }
        });

        minusButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Log.d("cal app","minus button clicked");
            }
        });

        multiplyButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Log.d("calc app","Multiply button clicked");
            }
        });

        divideButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Log.d("calc app","divide button clicked");
            }
        });








    }
}